#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AI_PlantBomb

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AI_PlantBomb.AI_PlantBomb_C
// 0x0010 (0x00B8 - 0x00A8)
class UAI_PlantBomb_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABombe_C*                               BombActor;                                         // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_AI_PlantBomb(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AI_PlantBomb_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AI_PlantBomb_C")
	}
	static class UAI_PlantBomb_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAI_PlantBomb_C>();
	}
};

}

