#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Alarm

#include "Basic.hpp"

#include "Alarm_classes.hpp"
#include "Alarm_parameters.hpp"


namespace SDK
{

// Function Alarm.Alarm_C.UpdatePower
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    On__0                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Provider                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::UpdatePower(bool On__0, class AActor* Provider)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "UpdatePower");

	Params::Alarm_C_UpdatePower Parms{};

	Parms.On__0 = On__0;
	Parms.Provider = Provider;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Alarm.Alarm_C.StartSiren (Multicast)
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_WaveClass                            EN_WaveClass                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::StartSiren__Multicast_(EN_WaveClass EN_WaveClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "StartSiren (Multicast)");

	Params::Alarm_C_StartSiren__Multicast_ Parms{};

	Parms.EN_WaveClass = EN_WaveClass;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Alarm.Alarm_C.SetLastSpecialZombieSpawnWave
// (Public, BlueprintCallable, BlueprintEvent)

void AAlarm_C::SetLastSpecialZombieSpawnWave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "SetLastSpecialZombieSpawnWave");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Alarm.Alarm_C.Set Zombie Rules
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_ZombieRules                          ZombieMode                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::Set_Zombie_Rules(EN_ZombieRules ZombieMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "Set Zombie Rules");

	Params::Alarm_C_Set_Zombie_Rules Parms{};

	Parms.ZombieMode = ZombieMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Alarm.Alarm_C.RegisterNewZombie
// (Public, BlueprintCallable, BlueprintEvent)

void AAlarm_C::RegisterNewZombie()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "RegisterNewZombie");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Alarm.Alarm_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AAlarm_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Alarm.Alarm_C.NewWaves
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Wave                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EN_WaveClass                            EN_WaveClass                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::NewWaves(int32 Wave, EN_WaveClass EN_WaveClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "NewWaves");

	Params::Alarm_C_NewWaves Parms{};

	Parms.Wave = Wave;
	Parms.EN_WaveClass = EN_WaveClass;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Alarm.Alarm_C.IsZombieCapReached?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Yes                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::IsZombieCapReached_(bool* Yes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "IsZombieCapReached?");

	Params::Alarm_C_IsZombieCapReached_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Yes != nullptr)
		*Yes = Parms.Yes;
}


// Function Alarm.Alarm_C.IncreaseTotalZombiesToSpawnInWave
// (Public, BlueprintCallable, BlueprintEvent)

void AAlarm_C::IncreaseTotalZombiesToSpawnInWave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "IncreaseTotalZombiesToSpawnInWave");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Alarm.Alarm_C.HandleWaveStarted
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   WaveNumber                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::HandleWaveStarted(int32 WaveNumber)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "HandleWaveStarted");

	Params::Alarm_C_HandleWaveStarted Parms{};

	Parms.WaveNumber = WaveNumber;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Alarm.Alarm_C.HandleEndWave
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   WaveNumber                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::HandleEndWave(int32 WaveNumber)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "HandleEndWave");

	Params::Alarm_C_HandleEndWave Parms{};

	Parms.WaveNumber = WaveNumber;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Alarm.Alarm_C.GetZombieMode
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_ZombieRules*                         ZombieMode                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::GetZombieMode(EN_ZombieRules* ZombieMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "GetZombieMode");

	Params::Alarm_C_GetZombieMode Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ZombieMode != nullptr)
		*ZombieMode = Parms.ZombieMode;
}


// Function Alarm.Alarm_C.GetWaves
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  CurrentWaves                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::GetWaves(int32* CurrentWaves)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "GetWaves");

	Params::Alarm_C_GetWaves Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CurrentWaves != nullptr)
		*CurrentWaves = Parms.CurrentWaves;
}


// Function Alarm.Alarm_C.GetMapInfo
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSTR_ZombieMapInfo*              MapInfo                                                (Parm, OutParm, HasGetValueTypeHash)

void AAlarm_C::GetMapInfo(struct FSTR_ZombieMapInfo* MapInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "GetMapInfo");

	Params::Alarm_C_GetMapInfo Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (MapInfo != nullptr)
		*MapInfo = std::move(Parms.MapInfo);
}


// Function Alarm.Alarm_C.ExecuteUbergraph_Alarm
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::ExecuteUbergraph_Alarm(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "ExecuteUbergraph_Alarm");

	Params::Alarm_C_ExecuteUbergraph_Alarm Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Alarm.Alarm_C.EndWave
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Wave                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EN_WaveClass                            EN_WaveClass                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::EndWave(int32 Wave, EN_WaveClass EN_WaveClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "EndWave");

	Params::Alarm_C_EndWave Parms{};

	Parms.Wave = Wave;
	Parms.EN_WaveClass = EN_WaveClass;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Alarm.Alarm_C.EndSiren (Server)
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void AAlarm_C::EndSiren__Server_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "EndSiren (Server)");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Alarm.Alarm_C.EndSiren (Multicast)
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_WaveClass                            EN_WaveClass                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::EndSiren__Multicast_(EN_WaveClass EN_WaveClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "EndSiren (Multicast)");

	Params::Alarm_C_EndSiren__Multicast_ Parms{};

	Parms.EN_WaveClass = EN_WaveClass;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Alarm.Alarm_C.ElectricalAction
// (Public, BlueprintCallable, BlueprintEvent)

void AAlarm_C::ElectricalAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "ElectricalAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Alarm.Alarm_C.ConnectionInfos
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              Color                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::ConnectionInfos(const struct FLinearColor& Color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "ConnectionInfos");

	Params::Alarm_C_ConnectionInfos Parms{};

	Parms.Color = std::move(Color);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Alarm.Alarm_C.CanSpawnSpecialZombie
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Yes                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::CanSpawnSpecialZombie(bool* Yes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "CanSpawnSpecialZombie");

	Params::Alarm_C_CanSpawnSpecialZombie Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Yes != nullptr)
		*Yes = Parms.Yes;
}


// Function Alarm.Alarm_C.BossAlreadyInMap?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Yes                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::BossAlreadyInMap_(bool* Yes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "BossAlreadyInMap?");

	Params::Alarm_C_BossAlreadyInMap_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Yes != nullptr)
		*Yes = Parms.Yes;
}


// Function Alarm.Alarm_C.AreAllWaveZombiesSpawned?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Yes                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAlarm_C::AreAllWaveZombiesSpawned_(bool* Yes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Alarm_C", "AreAllWaveZombiesSpawned?");

	Params::Alarm_C_AreAllWaveZombiesSpawned_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Yes != nullptr)
		*Yes = Parms.Yes;
}

}

