#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BFL_OnlinePresence

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BFL_OnlinePresence.BFL_OnlinePresence_C
// 0x0000 (0x0028 - 0x0028)
class UBFL_OnlinePresence_C final : public UBlueprintFunctionLibrary
{
public:
	static void PresenceParamsInGame(class FName LevelName, class UObject* __WorldContext, struct FSetPresenceParams* SetPresenceParams);
	static void PresenceParamsLoadingLevel(class FName LevelName, class UObject* __WorldContext, struct FSetPresenceParams* SetPresenceParams);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BFL_OnlinePresence_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BFL_OnlinePresence_C")
	}
	static class UBFL_OnlinePresence_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBFL_OnlinePresence_C>();
	}
};

}

