#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BFL_AchievementsHelper

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BFL_AchievementsHelper.BFL_AchievementsHelper_C
// 0x0000 (0x0028 - 0x0028)
class UBFL_AchievementsHelper_C final : public UBlueprintFunctionLibrary
{
public:
	static void ReportStatEvent(const struct FGameplayTag& StatTag, float IncrementValue, class UObject* __WorldContext);
	static void UnlockAchievement(const struct FGameplayTag& AchievementTag, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BFL_AchievementsHelper_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BFL_AchievementsHelper_C")
	}
	static class UBFL_AchievementsHelper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBFL_AchievementsHelper_C>();
	}
};

}

