#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DLSSApply

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_CustomSettingsApplyClass_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DLSSApply.BP_DLSSApply_C
// 0x0038 (0x0068 - 0x0030)
class UBP_DLSSApply_C final : public UBP_CustomSettingsApplyClass_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_DLSSApply_C;                     // 0x0030(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FString                                 DLSSEnable;                                        // 0x0038(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 DLSSQuality;                                       // 0x0048(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 DLSSCommand;                                       // 0x0058(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DLSSApply(int32 EntryPoint);
	void OnApply(class UPDA_SettingsData_C* SettingsData, const struct FFValueTypes& Value, class UBP_SettingsManager_C* SettingsManager);
	void OnDelayedEnableDLSS();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DLSSApply_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DLSSApply_C")
	}
	static class UBP_DLSSApply_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DLSSApply_C>();
	}
};

}

