#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Gramophone

#include "Basic.hpp"

#include "BP_Gramophone_classes.hpp"
#include "BP_Gramophone_parameters.hpp"


namespace SDK
{

// Function BP_Gramophone.BP_Gramophone_C.UpdateGramophone
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Open__0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::UpdateGramophone(bool Open__0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "UpdateGramophone");

	Params::BP_Gramophone_C_UpdateGramophone Parms{};

	Parms.Open__0 = Open__0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Gramophone.BP_Gramophone_C.Timeline__UpdateFunc
// (BlueprintEvent)

void ABP_Gramophone_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Gramophone.BP_Gramophone_C.Timeline__FinishedFunc
// (BlueprintEvent)

void ABP_Gramophone_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Gramophone.BP_Gramophone_C.SwitchAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimMontage**                    In                                                     (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UAnimMontage**                    Out                                                    (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class USoundCue**                       InSound                                                (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class USoundCue**                       OutSound                                               (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::SwitchAnimation(class UAnimMontage** In, class UAnimMontage** Out, class USoundCue** InSound, class USoundCue** OutSound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "SwitchAnimation");

	Params::BP_Gramophone_C_SwitchAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (In != nullptr)
		*In = Parms.In;

	if (Out != nullptr)
		*Out = Parms.Out;

	if (InSound != nullptr)
		*InSound = Parms.InSound;

	if (OutSound != nullptr)
		*OutSound = Parms.OutSound;
}


// Function BP_Gramophone.BP_Gramophone_C.RandomLocation (Server)
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_Gramophone_C::RandomLocation__Server_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "RandomLocation (Server)");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Gramophone.BP_Gramophone_C.Pickup
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Owner_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::Pickup(class AActor* Owner_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "Pickup");

	Params::BP_Gramophone_C_Pickup Parms{};

	Parms.Owner_0 = Owner_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Gramophone.BP_Gramophone_C.OnRep_Open?
// (BlueprintCallable, BlueprintEvent)

void ABP_Gramophone_C::OnRep_Open_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "OnRep_Open?");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Gramophone.BP_Gramophone_C.LeftClickReleaseEvent
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Gramophone_C::LeftClickReleaseEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "LeftClickReleaseEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Gramophone.BP_Gramophone_C.LeftClickEvent
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Gramophone_C::LeftClickEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "LeftClickEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Gramophone.BP_Gramophone_C.Item Focus
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Instigator_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::Item_Focus(class AActor* Instigator_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "Item Focus");

	Params::BP_Gramophone_C_Item_Focus Parms{};

	Parms.Instigator_0 = Instigator_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Gramophone.BP_Gramophone_C.IsDefaultHandle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsDefaultHandle_                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::IsDefaultHandle(bool* IsDefaultHandle_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "IsDefaultHandle");

	Params::BP_Gramophone_C_IsDefaultHandle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsDefaultHandle_ != nullptr)
		*IsDefaultHandle_ = Parms.IsDefaultHandle_;
}


// Function BP_Gramophone.BP_Gramophone_C.InterractDoor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Z_Angle                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ResetDoor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::InterractDoor(double Z_Angle, bool ResetDoor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "InterractDoor");

	Params::BP_Gramophone_C_InterractDoor Parms{};

	Parms.Z_Angle = Z_Angle;
	Parms.ResetDoor = ResetDoor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Gramophone.BP_Gramophone_C.Interract (Server)
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_Gramophone_C::Interract__Server_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "Interract (Server)");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Gramophone.BP_Gramophone_C.Interract
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            Owner_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::Interract(class APawn* Owner_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "Interract");

	Params::BP_Gramophone_C_Interract Parms{};

	Parms.Owner_0 = Owner_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Gramophone.BP_Gramophone_C.GetSocketToAttach
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName*                            SocketToAttach                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::GetSocketToAttach(class FName* SocketToAttach)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "GetSocketToAttach");

	Params::BP_Gramophone_C_GetSocketToAttach Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SocketToAttach != nullptr)
		*SocketToAttach = Parms.SocketToAttach;
}


// Function BP_Gramophone.BP_Gramophone_C.GetOverlay
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EALS_OverlayState*                      Overlay                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::GetOverlay(EALS_OverlayState* Overlay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "GetOverlay");

	Params::BP_Gramophone_C_GetOverlay Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Overlay != nullptr)
		*Overlay = Parms.Overlay;
}


// Function BP_Gramophone.BP_Gramophone_C.GetOffset
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FTransform*                      Offset                                                 (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::GetOffset(struct FTransform* Offset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "GetOffset");

	Params::BP_Gramophone_C_GetOffset Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Offset != nullptr)
		*Offset = std::move(Parms.Offset);
}


// Function BP_Gramophone.BP_Gramophone_C.GetItemPriority
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  Priority                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::GetItemPriority(int32* Priority)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "GetItemPriority");

	Params::BP_Gramophone_C_GetItemPriority Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Priority != nullptr)
		*Priority = Parms.Priority;
}


// Function BP_Gramophone.BP_Gramophone_C.ExecuteUbergraph_BP_Gramophone
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::ExecuteUbergraph_BP_Gramophone(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "ExecuteUbergraph_BP_Gramophone");

	Params::BP_Gramophone_C_ExecuteUbergraph_BP_Gramophone Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Gramophone.BP_Gramophone_C.Drop
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Delay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::Drop(double Delay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "Drop");

	Params::BP_Gramophone_C_Drop Parms{};

	Parms.Delay = Delay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Gramophone.BP_Gramophone_C.CanSwap?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsItemSwap_                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::CanSwap_(bool* IsItemSwap_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "CanSwap?");

	Params::BP_Gramophone_C_CanSwap_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsItemSwap_ != nullptr)
		*IsItemSwap_ = Parms.IsItemSwap_;
}


// Function BP_Gramophone.BP_Gramophone_C.CanPickup
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   Pickup_                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::CanPickup(class ACharacter* Player, bool* Pickup_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "CanPickup");

	Params::BP_Gramophone_C_CanPickup Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);

	if (Pickup_ != nullptr)
		*Pickup_ = Parms.Pickup_;
}


// Function BP_Gramophone.BP_Gramophone_C.CanInterract
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Instigator_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   Interract_                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Gramophone_C::CanInterract(class AActor* Instigator_0, bool* Interract_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Gramophone_C", "CanInterract");

	Params::BP_Gramophone_C_CanInterract Parms{};

	Parms.Instigator_0 = Instigator_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Interract_ != nullptr)
		*Interract_ = Parms.Interract_;
}

}

