#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: M4A1

#include "Basic.hpp"

#include "ALS_OverlayState_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function M4A1.M4a1_C.GetOffset
// 0x00C0 (0x00C0 - 0x0000)
struct M4a1_C_GetOffset final
{
public:
	struct FTransform                             Offset;                                            // 0x0000(0x0060)(Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0060(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function M4A1.M4a1_C.GetOverlay
// 0x0001 (0x0001 - 0x0000)
struct M4a1_C_GetOverlay final
{
public:
	EALS_OverlayState                             Overlay;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

