#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpectatorHud

#include "Basic.hpp"

#include "SpectatorHud_classes.hpp"
#include "SpectatorHud_parameters.hpp"


namespace SDK
{

// Function SpectatorHud.SpectatorHud_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USpectatorHud_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpectatorHud_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SpectatorHud.SpectatorHud_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USpectatorHud_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpectatorHud_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SpectatorHud.SpectatorHud_C.ExecuteUbergraph_SpectatorHud
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USpectatorHud_C::ExecuteUbergraph_SpectatorHud(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpectatorHud_C", "ExecuteUbergraph_SpectatorHud");

	Params::SpectatorHud_C_ExecuteUbergraph_SpectatorHud Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SpectatorHud.SpectatorHud_C.Finished_23C14BBB4F513975D5E10A85724891B0
// (BlueprintCallable, BlueprintEvent)

void USpectatorHud_C::Finished_23C14BBB4F513975D5E10A85724891B0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpectatorHud_C", "Finished_23C14BBB4F513975D5E10A85724891B0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SpectatorHud.SpectatorHud_C.Finished_BA4C84F14F06B18414BD7E9E56752070
// (BlueprintCallable, BlueprintEvent)

void USpectatorHud_C::Finished_BA4C84F14F06B18414BD7E9E56752070()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpectatorHud_C", "Finished_BA4C84F14F06B18414BD7E9E56752070");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SpectatorHud.SpectatorHud_C.HideSpectatorHudAnimation
// (BlueprintCallable, BlueprintEvent)

void USpectatorHud_C::HideSpectatorHudAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpectatorHud_C", "HideSpectatorHudAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SpectatorHud.SpectatorHud_C.OnLoaded_A860F0C549D0EDBF7CEF2691542CB4C1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USpectatorHud_C::OnLoaded_A860F0C549D0EDBF7CEF2691542CB4C1(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpectatorHud_C", "OnLoaded_A860F0C549D0EDBF7CEF2691542CB4C1");

	Params::SpectatorHud_C_OnLoaded_A860F0C549D0EDBF7CEF2691542CB4C1 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SpectatorHud.SpectatorHud_C.SwitchPlayers
// (BlueprintCallable, BlueprintEvent)

void USpectatorHud_C::SwitchPlayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpectatorHud_C", "SwitchPlayers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SpectatorHud.SpectatorHud_C.UpdateStatInfo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USpectatorHud_C::UpdateStatInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpectatorHud_C", "UpdateStatInfo");

	UObject::ProcessEvent(Func, nullptr);
}

}

