#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_ZoneData

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Struct_ZoneData.Struct_ZoneData
// 0x0020 (0x0020 - 0x0000)
struct FStruct_ZoneData final
{
public:
	TArray<class ABP_ZombieSpawner_C*>            ConnectedSpawners_4_A936AED1401C8F08CC73238D47321E07; // 0x0000(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	double                                        MinSpawnFrequency_9_9F488B424440F60C33446493B36A7CAD; // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MaxSpawnFrequency_10_7E3958B34EAB166EE4449F8D84FEBF50; // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

