#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_SpawnerWeigth

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Struct_SpawnerWeigth.Struct_SpawnerWeigth
// 0x0010 (0x0010 - 0x0000)
struct FStruct_SpawnerWeigth final
{
public:
	class ABP_ZombieSpawner_C*                    Spawner_3_6B6551B84DB662011CD844B7CEBB1329;        // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	double                                        Weight_5_A3B9ACB643DA5F18B6720EA0547811A3;         // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

